# SPDX-FileCopyrightText: Â© 2024 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "fotema_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
base64 = "0.22.1"
chrono = "0.4.37"
fast_image_resize = { version = "4.0.0", features = ["image"] }
ffmpeg-next = "7.0.1"
gdk4 = "0.8.2"
gio = "0.19.5"
glycin = "1.0.2"
gtk = "0.18.1"
image = "0.25.0"
kamadak-exif = "0.5.5"
rayon = "1.10.0"
refinery = { version = "0.8.14", features = ["rusqlite"] }
rusqlite = { version = "0.31.0", features = ["bundled", "chrono"] }
strum = { version = "0.26.2", features = ["derive"] }
tempfile = "3.10.1"
tracing = "0.1.40"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.10.1"

