# SPDX-FileCopyrightText: Â© 2024 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "fotema_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
chrono = "0.4.37"
fast_image_resize = { version = "4.2.1", features = ["image"] }
ffmpeg-next = "7.0.4"
gdk4 = "0.8.2"
gio = "0.19.5"
glycin = "1.0.2"
gtk = "0.18.1"
h3o = "0.6.4"
image = "0.25.2"
half = "2.4.1"
kamadak-exif = "0.5.5"
rayon = "1.10.0"
refinery = { version = "0.8.14", features = ["rusqlite"] }
rusqlite = { version = "0.31.0", features = ["bundled", "chrono"] }
rust-faces = {git = "https://github.com/blissd/rust-faces.git", branch = "patch", features = ["viz"]}
sm_motion_photo = "0.1.5"
strum = { version = "0.26.2", features = ["derive"] }
tempfile = "3.10.1"
tracing = "0.1.40"
walkdir = "2.5.0"
opencv = {version = "0.92.1", default-features = false, features = ["clang-runtime", "objdetect", "imgcodecs", "dnn"]}
itertools = "0.13.0"
reqwest = { version = "0.12.5", features = ["blocking"] }

[dev-dependencies]
tempfile = "3.10.1"

